### ISSUE TITLE
Instructor Reporting Page errors on "All" tdfs selected

### ISSUE THREAD

**Issue by andrewtackett** [memphis-iis/mofacts-ies#92]
Exception while invoking method 'getStudentPerformanceForClassAndTdf' TypeError: Cannot read property 'tdfs' of undefined
    at server/methods.js:477:34
    at Array.forEach (<anonymous>)
    at MethodInvocation.getStudentPerformanceForClassAndTdf (server/methods.js:466:33)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
Exception while invoking method 'getStudentPerformanceForClassAndTdf' TypeError: Cannot read property 'tdfs' of undefined
    at server/methods.js:477:34
    at Array.forEach (<anonymous>)
    at MethodInvocation.getStudentPerformanceForClassAndTdf (server/methods.js:466:33)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43

**Comment by wscarter** [comment]
2088aa8f71f68963becce52668cee0042f555dc9
