### ISSUE TITLE
Unverified emails cause error report syncedcron to fail

### ISSUE THREAD

**Issue by wscarter** [memphis-iis/mofacts-ies#99]
```
 {"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Exception \"Send Error Report Summaries\" Error: Message failed: 554 Message rejected: Email address is not verified. The following identities failed the check in region US-WEST-2: unverified@email.com\n    at SMTPConnection._formatError (/var/www/mofacts/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mai      ler/lib/smtp-connection/index.js:558:19)\n    at SMTPConnection._actionSMTPStream (/var/www/mofacts/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/      index.js:1386:34)\n    at SMTPConnection._responseActions.push.str (/var/www/mofacts/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:908:22      )\n    at SMTPConnection._processResponse (/var/www/mofacts/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:707:20)\n    at SMTPConnection.      _onData (/var/www/mofacts/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:510:14)\n    at TLSSocket._socket.on.chunk (/var/www/mofacts/bund      le/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:658:51)\n    at emitOne (events.js:116:13)\n    at TLSSocket.emit (events.js:211:7)\n    at add      Chunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at TLSSocket.Readable.push (_stream_readable.js:208:10)\n    at TLSWrap.onread (net.js:597:20)","time":{      "$date":1575644400665},"level":"info"}
```
Error report emails are being sent repeatedly and are not marked as sent.  An error is being thrown from `percolate_synced-cron.js` from percolate package but the job is defined in `methods.js`.  Emails should be verified (or exception should be caught) before attempting to send messages to prevent the job loop from terminating early.

**Comment by wscarter** [comment]
added try-catch to error reports job
657358c
